backend:
  name: github
  repo: lucasmallmann/lucasmallmann
  branch: master

media_folder: static/assets/posts
public_folder: /assets/posts
media_folder_relative: true
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    slug: '{{year}}-{{month}}-{{day}}--{{slug}}' # filename template
    fields:
      - {
          name: date,
          label: Date,
          widget: datetime,
          format: YYYY-MM-DD hh:mm:ss,
        }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list, default: [''] }
      - { name: image, label: Cover, widget: image }
